<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * DemandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandRepository extends EntityRepository
{
	public function findByService($service, $attestation)
	{
		$qb = $this->createQueryBuilder('d')
			->join('d.employee', 'e')
			->where('e.service = :service' )
			->andWhere('d.typeAttestation = :attestation')
			->setParameter('service', $service)
			->setParameter('attestation', $attestation)
			->getQuery()
			->getResult()
			;
		return $qb;
	}
	public function findByMatricule($matricule)
	{
		$qb = $this->createQueryBuilder('d')
			->join('d.employee', 'e')
			->where('e.matricule = :matricule')
			->setParameter('matricule', $matricule)
			->getQuery()
			->getResult()
			;
		return $qb;
	}
}
