<?php

namespace AppBundle\Repository;

/**
 * TypeAttestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAttestationRepository extends \Doctrine\ORM\EntityRepository
{
}
